condense_wildcard_suffixes = true
error_on_line_overflow = true
# error_on_unformatted = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
wrap_comments = true
